# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

# Disabled: CI deploy to Fly.io is not used for the UI repo
name: disabled-fly-deploy
on:
  workflow_dispatch:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fly deploy workflow disabled for this repository."
